[tool.poetry]
name = "census-istat"
version = "0.2.0"
description = ""
authors = ["Massimiliano Moraca <info@massimilianomoraca.it>"]
readme = "README.md"
packages = [{include = "census_istat"}]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.2.1"
pandas = "^1.5.3"
geopandas = "^0.12.2"
tqdm = "^4.64.1"
chardet = "^5.1.0"
requests = "^2.28.2"
fsspec = "^2023.1.0"
openpyxl = "^3.1.1"
xlrd = "^2.0.1"
dask = {extras = ["distributed"], version = "^2023.2.0"}


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
notebook = "^6.5.2"
jupyter-server-proxy = "^3.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
