site_name: Census ISTAT
site_url: https://maxdragonheart.github.io/census_istat/
repo_url: https://github.com/MaxDragonheart/census_istat
site_description: Con census_istat puoi ottenere facilmente il set di dati riferiti ai censimenti ISTAT in cui sono stati rilasciati anche i dati delle celle censuarie.
site_author: Massimiliano Moraca
nav:
  - Home: ./index.md
  - Documentazione: ./documentation/intro.md
  - Licenza: ./LICENSE.md
theme:
  name: material
  palette:
    primary: blue
  highlightjs: true
  hljs_languages:
    - python
  include_homepage_in_sidebar: true
  locale: it
markdown_extensions:
  - abbr
  - admonition
plugins:
    - search:
        indexing: 'full'